# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/shazi/Desktop/EmbeddedLab4_RemoteAccessFiles/Lab4/zybo_old_board.xdc

# IP: ip/picture/picture.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==picture || ORIG_REF_NAME==picture} -quiet] -quiet
